[package]
name = "ExampleProposal"
version = "0.0.1"

[addresses]
example_proposal = "0x0"
pool_manager = "0x0"
wormhole_bridge = "0x0"
governance = "0x0"
lending = "0x0"
app_manager = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "79100a5687881eef489f347629bf5b19e417cc8e"

[dependencies.AppManager]
local = "../app_manager"

[dependencies.Governance]
local = "../governance"

[dependencies.WormholeBridge]
local = "../../wormhole_bridge"

[dependencies.PoolManager]
local = "../pool_manager"

[dependencies.Lending]
local = "../lending"
