[package]
name = "ExternalInterfaces"
version = "0.0.1"

[addresses]
external_interfaces = "0x0"
pool_manager = "0x0"
user_manager = "0x0"
dola_types = "0x0"
lending_core = "0x1"
ray_math = "0x0"
oracle = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.PoolManager]
local = "../pool_manager"

[dependencies.UserManager]
local = "../user_manager"

[dependencies.LendingCore]
local = "../lending_core"

[dependencies.RayMath]
local = "../ray_math"

[dependencies.Oracle]
local = "../oracle"

[dependencies.DolaTypes]
local = "../dola_types"
