[package]
name = "ExternalInterfaces"
version = "0.0.1"

[addresses]
external_interfaces = "0x0"
pool_manager = "0x0"
user_manager = "0x0"
dola_types = "0x0"
lending = "0x0"
oracle = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "a8af20d94e951ecfb6d0cd47c23cf6393013d8a8"

[dependencies.PoolManager]
local = "../omnicore/pool_manager"

[dependencies.UserManager]
local = "../omnicore/user_manager"

[dependencies.Lending]
local = "../omnicore/lending"

[dependencies.Oracle]
local = "../omnicore/oracle"

[dependencies.DolaTypes]
local = "../dola_types"
