[package]
name = "ExternalInterfaces"
version = "0.0.1"

[addresses]
external_interfaces = "0x0"
pool_manager = "0x0"
user_manager = "0x0"
dola_types = "0x0"
lending_core = "0x0"
oracle = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "cece99272f261d046c64510812e36404e7deb661"

[dependencies.PoolManager]
local = "../omnicore/pool_manager"

[dependencies.UserManager]
local = "../omnicore/user_manager"

[dependencies.LendingCore]
local = "../omnicore/lending_core"

[dependencies.Oracle]
local = "../omnicore/oracle"

[dependencies.DolaTypes]
local = "../dola_types"
