[package]
name = "LendingPortal"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "bf4065c04b8d7462047955abeea0aa9e11221088" }
Wormhole = { git = "https://github.com/OmniBTC/wormhole.git", subdir = "sui/wormhole", rev = "ade434c9326385f4ab23fe314a9bab34e074ad16" }
OmniPool = { local = "../omnipool" }
Serde = { local = "../serde" }
WormholeBridge = { local = "../wormhole_bridge" }

[addresses]
lending = "0x0"
serde = "0x0"
wormhole_bridge = "0x0"
wormhole = "0x0"
omnipool = "0x0"
sui = "0x2"
