[package]
name = "Serde"
version = "0.0.1"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
serde = "0x1d2c5ca9299e6e6222ab126750797e18ba0bfe55cf2aa431ddfd7f2778f17ff7"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
