[package]
name = "DolaTypes"
version = "0.0.1"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
dola_types = "_"
serde = "_"

[dev-addresses]
# sha256 "OmniBTC | DolaProtocol | DolaTypes"
dola_types = "0x8b97658dd9f52ad00684467269e5dee7b3e6e7f763f9b1da68e7310a07794b39"
serde = "0xcb56c63012804b0defed1d1196b817aec2857df516b39355a2e35fb5d65d2fbe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "cb4ba0a57c998c60cbab65af31a64875d2588ca5"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Serde]
local = "../serde"
