[package]
name = "GenesisProposal"
version = "0.0.1"

[addresses]
genesis_proposal = "0x0"
pool_manager = "0x0"
user_manager = "0x0"
wormhole = "0x0"
wormhole_bridge = "0x0"
governance = "0x0"
lending_core = "0x0"
dola_portal = "0x0"
app_manager = "0x0"
oracle = "0x0"
dola_types = "0x0"
omnipool = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "b63532e36df5b1fcccff3893509259494c719a78"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "83c198bfcc6774cc95a0f19f8eed232b8c9fd506"

[dependencies.AppManager]
local = "../../app_manager"

[dependencies.Governance]
local = "../../governance"

[dependencies.WormholeBridge]
local = "../../wormhole_bridge"

[dependencies.PoolManager]
local = "../../pool_manager"

[dependencies.LendingCore]
local = "../../lending_core"

[dependencies.DolaPortal]
local = "../../dola_portal"

[dependencies.Oracle]
local = "../../oracle"

[dependencies.UserManager]
local = "../../user_manager"

[dependencies.DolaTypes]
local = "../../dola_types"

[dependencies.OmniPool]
local = "../../omnipool"
