[package]
name = "GenesisProposal"
version = "0.0.1"

[addresses]
genesis_proposal = "0x0"
pool_manager = "0x0"
user_manager = "0x0"
wormhole = "0x15e1e51cb59fe1f987b037da12745a278855c8ac73050f4f194466096a0ca05b"
wormhole_adapter_core = "0x1"
system_core = "0x0"
governance = "0x0"
lending_core = "0x1"
dola_portal = "0x0"
app_manager = "0x0"
oracle = "0x0"
dola_types = "0x0"
omnipool = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "3a70c4374090b020b95465787f3220a95d8ab0ba"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole"
subdir = "sui/wormhole"
rev = "ee0bd18ffca678b3598a0644a643aac0e77effc0"

[dependencies.AppManager]
local = "../../dola_protocol/sources/app_manager"

[dependencies.Governance]
local = "../../dola_protocol/sources/governance"

[dependencies.WormholeAdapterCore]
local = "../../dola_protocol/sources/wormhole_adapter_core"

[dependencies.PoolManager]
local = "../../dola_protocol/sources/pool_manager"

[dependencies.LendingCore]
local = "../../dola_protocol/sources/lending_core"

[dependencies.SystemCore]
local = "../../dola_protocol/sources/system_core"

[dependencies.DolaPortal]
local = "../../dola_protocol/sources/dola_portal"

[dependencies.Oracle]
local = "../../dola_protocol/sources/oracle"

[dependencies.UserManager]
local = "../../dola_protocol/sources/user_manager"

[dependencies.DolaTypes]
local = "../../dola_protocol/sources/dola_types"

[dependencies.OmniPool]
local = "../../dola_protocol/sources/omnipool"
