[package]
name = "LendingCore"
version = "0.0.1"

[addresses]
lending_core = "0x1"
wormhole_adapter_core = "0x1"
user_manager = "0x0"
pool_manager = "0x0"
app_manager = "0x0"
governance = "0x0"
oracle = "0x0"
serde = "0x0"
wormhole = "0x0"
ray_math = "0x0"
dola_types = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "d79f1f6dec84971a95c7df663fefa13bf7fda336"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "dcceff545df0d9dd7ce537f51373d3cc6d20d00d"

[dependencies.DolaTypes]
local = "../dola_types"

[dependencies.Serde]
local = "../serde"

[dependencies.RayMath]
local = "../ray_math"

[dependencies.WormholeAdapterCore]
local = "../wormhole_adapter_core"

[dependencies.AppManager]
local = "../app_manager"

[dependencies.PoolManager]
local = "../pool_manager"

[dependencies.Governance]
local = "../governance"

[dependencies.Oracle]
local = "../oracle"

[dependencies.UserManager]
local = "../user_manager"
