[package]
name = "PoolManager"
version = "0.0.1"

[addresses]
pool_manager = "0x0"
governance = "0x0"
dola_types = "0x0"
serde = "0x0"
ray_math = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "3a70c4374090b020b95465787f3220a95d8ab0ba"

[dependencies.Serde]
local = "../serde"

[dependencies.RayMath]
local = "../ray_math"

[dependencies.Governance]
local = "../governance"

[dependencies.DolaTypes]
local = "../dola_types"
