[package]
name = "UserManager"
version = "0.0.1"

[addresses]
user_manager = "0x0"
governance = "0x0"
dola_types = "0x0"
serde = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "b63532e36df5b1fcccff3893509259494c719a78"

[dependencies.DolaTypes]
local = "../dola_types"

[dependencies.Serde]
local = "../serde"

[dependencies.Governance]
local = "../governance"
