# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  default: development
  development:
    wormhole_chainid: 0
    wormhole: "0x0000000000000000000000000000000000000000"
  goerli:
    wormhole_chainid: 2
    wormhole: "0x706abc4E45D419950511e474C7B9Ed348A4a716c"
  bsc-test:
    wormhole_chainid: 4
    wormhole: "0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D"
    usdt: "0x6edEb01556116295Ec48B1c125c59d49C2EA7bfC"
    usdt_pool: "0x9a2E6b46a6dA57bb2aD6e411aB0d497DAd8fB595"
    btc: "0x7Ccc725Ed9F881F112Eff42012838667C3A78B66"
    btc_pool: "0x1e9C3aA2bfbc57d125b657Ca4284B6e04c6Df1c2"
  polygon-test:
    wormhole_chainid: 5
    wormhole: "0x0CBE91CF822c73C2315FB05100C2F714765d5c20"
  avax-test:
    wormhole_chainid: 6
    wormhole: "0x7bbcE28e64B3F8b84d876Ab298393c38ad7aac4C"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
