# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
# automatically fetch contract sources from Etherscan
#autofetch_sources: True
dotenv: .env
networks:
  default: development
  development:
    wormhole_chainid: 0
    wormhole: "0x0000000000000000000000000000000000000000"
  goerli:
    wormhole_chainid: 2
    wormhole: "0x706abc4E45D419950511e474C7B9Ed348A4a716c"
  bsc-test:
    scan_rpc_url: "https://api-testnet.bscscan.com/api"
    wormhole_chainid: 4
    wormhole: "0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D"
    btc: "0x534BF426a64d93d4CaCeCFa1Eb1FD1aCC2A988a5"
    usdt: "0xe6606196DfcE08E0B0945BDbfECDF5952F8C2cfC"
    usdc: "0x1b619121e3918489C3214917f23AA18c5DC877fe"
  polygon-test:
    scan_rpc_url: "https://api-testnet.polygonscan.com/api"
    wormhole_chainid: 5
    wormhole: "0x0CBE91CF822c73C2315FB05100C2F714765d5c20"
    btc: "0x9d6b8FeCDe95C9E222a388BdAC04d4b57CcEc27F"
    usdt: "0x896e955002262debAdB35f8a1F23B79284D0118F"
    usdc: "0xcFD3A43F83E7A0d932c446A410be93fFf668FEc8"
  polygon-zk-test:
    # Maintenance in progress
    scan_rpc_url: "https://api-testnet-zkevm.polygonscan.com/api"
    wormhole_chainid: 7
    wormhole: "0x0000000000000000000000000000000000000000"
    btc: "0x9895bcd049eE00560599b1458fC2436793E3E011"
    usdt: "0xABC8849BB0fF39EDF2CfC41d23C307f0FEaE1714"
    usdc: "0x2bb68D45ce273e5eed8D10193B98a9e33259f2B1"
  avax-test:
    wormhole_chainid: 6
    wormhole: "0x7bbcE28e64B3F8b84d876Ab298393c38ad7aac4C"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}