compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
dotenv: .env
networks:
  optimism-main:
    dola_chain_id: 24
    core_emitter: '0xabbce6c0c2c7cd213f4c69f8a685f6dfc1848b6e3f31dd15872f4e777d5b3e86'
    pools:
      ETH:
        dola_chain_id: 24
        dola_pool_id: 4
        pool_address: '0x0000000000000000000000000000000000000000'
        pool_name: ETH
        pool_weight: 1
      USDC:
        dola_chain_id: 24
        dola_pool_id: 2
        pool_address: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607'
        pool_name: USDC
        pool_weight: 1
      USDT:
        dola_chain_id: 24
        dola_pool_id: 1
        pool_address: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58'
        pool_name: USDT
        pool_weight: 1
      WBTC:
        dola_chain_id: 24
        dola_pool_id: 0
        pool_address: '0x68f180fcCe6836688e9084f035309E29Bf0A2095'
        pool_name: WBTC
        pool_weight: 1
      OP:
        dola_chain_id: 24
        dola_pool_id: 7
        pool_address: '0x4200000000000000000000000000000000000042'
        pool_name: OP
        pool_weight: 1
    scan_rpc_url: https://api-optimistic.etherscan.io/api
    graphql_url: https://api.studio.thegraph.com/query/48530/opdolarelayer/version/latest
    tokens:
      ETH:
        address: '0x0000000000000000000000000000000000000000'
        decimals: 18
        dola_pool_id: 4
      OP:
        address: '0x4200000000000000000000000000000000000042'
        decimals: 18
        dola_pool_id: 7
      USDC:
        address: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607'
        decimals: 6
        dola_pool_id: 2
      USDT:
        address: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58'
        decimals: 6
        dola_pool_id: 1
      WBTC:
        address: '0x68f180fcCe6836688e9084f035309E29Bf0A2095'
        decimals: 8
        dola_pool_id: 0
    wormhole: '0xEe91C335eab126dF5fDB3797EA9d6aD93aeC9722'
    wormhole_chainid: 24
    wormhole_adapter_pool: '0x94650D61b940496b1BD88767b7B541b1121e0cCF'
    lending_portal: '0xD3588acd2A3b69E84a127F92dA3b5f8d81951c16'
    system_portal: '0x3dd7b63a9b52761F89bd1bBBd31324242A0DaE01'
    wormhole_instant_consistency: 200
    wormhole_finality_consistency: 200
  arbitrum-main:
    core_emitter: '0xabbce6c0c2c7cd213f4c69f8a685f6dfc1848b6e3f31dd15872f4e777d5b3e86'
    dola_chain_id: 23
    lending_portal: '0xEBb6a1d17Ae9A276EdE95bF6B8fC6527fa2dF737'
    pools:
      ETH:
        dola_chain_id: 23
        dola_pool_id: 4
        pool_address: '0x0000000000000000000000000000000000000000'
        pool_name: ETH
        pool_weight: 1
      ARB:
        dola_chain_id: 23
        dola_pool_id: 6
        pool_address: '0x912CE59144191C1204E64559FE8253a0e49E6548'
        pool_name: ARB
        pool_weight: 1
      USDC:
        dola_chain_id: 23
        dola_pool_id: 2
        pool_address: '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8'
        pool_name: USDC
        pool_weight: 1
      USDT:
        dola_chain_id: 23
        dola_pool_id: 1
        pool_address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'
        pool_name: USDT
        pool_weight: 1
      WBTC:
        dola_chain_id: 23
        dola_pool_id: 0
        pool_address: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f'
        pool_name: WBTC
        pool_weight: 1
    scan_rpc_url: https://api.arbiscan.io/api
    graphql_url: https://api.studio.thegraph.com/query/48530/arbdolarelayer/version/latest
    system_portal: '0x6F5b4Bc793aE7213564501aB22c714e39f5D2BAC'
    tokens:
      ETH:
        address: '0x0000000000000000000000000000000000000000'
        decimals: 18
        dola_pool_id: 4
      ARB:
        address: '0x912CE59144191C1204E64559FE8253a0e49E6548'
        decimals: 18
        dola_pool_id: 6
      USDC:
        address: '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8'
        decimals: 6
        dola_pool_id: 2
      USDT:
        address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'
        decimals: 6
        dola_pool_id: 1
      WBTC:
        address: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f'
        decimals: 8
        dola_pool_id: 0
    wormhole: '0xa5f208e072434bC67592E4C49C1B991BA79BCA46'
    wormhole_adapter_pool: '0x098D26E4d2E98C1Dde14C543Eb6804Fd98Af9CB4'
    wormhole_chainid: 23
    wormhole_instant_consistency: 200
    wormhole_finality_consistency: 200
  arbitrum-test:
    core_emitter: '0xd978abe951a42fb60f00015718efa1e1a9f2256676419fb66551db2816d983b7'
    scan_rpc_url: https://api-goerli.arbiscan.io/api
    wormhole: '0xC7A204bDBFe983FCD8d8E61D02b475D4073fF97e'
    wormhole_chainid: 23
    wormhole_finality: 200
  avax-test:
    wormhole: '0x7bbcE28e64B3F8b84d876Ab298393c38ad7aac4C'
    wormhole_chainid: 6
    core_emitter: '0x4f9f241cd3a249e0ef3d9ece8b1cd464c38c95d6d65c11a2ddd5645632e6e8a0'
    lending_portal: '0x715700167fE79d4777D2d39b1B5ddE579FD782D9'
    system_portal: '0x3C1ee850d33c1C9E30F1dCD5f6E034b86Fda02C7'
    graphql_url: https://api.studio.thegraph.com/query/48530/fujidola/version/latest
    pools:
      USDC:
        dola_chain_id: 6
        dola_pool_id: 2
        pool_address: '0x92682ce0591b788767dCF2997df74Ac50C0b50CD'
        pool_name: USDC
        pool_weight: 1
      USDT:
        dola_chain_id: 6
        dola_pool_id: 1
        pool_address: '0x966CCd1ae8b81c7fEB27ffF65c630D9F8cFfBf28'
        pool_name: USDT
        pool_weight: 1
      WBTC:
        dola_chain_id: 6
        dola_pool_id: 0
        pool_address: '0x351B7351F2DE7Cb58b37CEDd4c61A7B804F58170'
        pool_name: WBTC
        pool_weight: 1
    tokens:
      USDC:
        address: '0x92682ce0591b788767dCF2997df74Ac50C0b50CD'
        decimals: 18
        dola_pool_id: 2
      USDT:
        address: '0x966CCd1ae8b81c7fEB27ffF65c630D9F8cFfBf28'
        decimals: 18
        dola_pool_id: 1
      WBTC:
        address: '0x351B7351F2DE7Cb58b37CEDd4c61A7B804F58170'
        decimals: 18
        dola_pool_id: 0
    wormhole_adapter_pool: '0xd5dc5E3d1119cC1FBFB0Ec2613DD2C839aB79322'
    wormhole_instant_consistency: 200
    wormhole_finality_consistency: 200
  bsc-test:
    btc: '0x534BF426a64d93d4CaCeCFa1Eb1FD1aCC2A988a5'
    lending_portal: '0x3bDCd3dE2FAaEed58Ae5E9FD5e7c92Bfa938B5d0'
    scan_rpc_url: https://api-testnet.bscscan.com/api
    system_portal: '0xbA6f703c67f60bD90f9DA55c4318809Fae88Cd69'
    usdc: '0xA8Bc57f9f9Fd81a7eed9b7C2C91e5E299559D0d9'
    usdt: '0x6d615704201811c5e6575f99d263d8ba1CF0ccE2'
    wbtc: '0xCB9a33266F16B368FD90D43993F25F475622F01F'
    wormhole: '0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D'
    wormhole_adapter_pool: '0x2145b48c726e07850c6E4E59cD7c10A71f1Cf0b5'
    wormhole_chainid: 4
    wormhole_finality: 200
  default: development
  development:
    wormhole: '0x0000000000000000000000000000000000000000'
    wormhole_chainid: 0
  goerli:
    wormhole: '0x706abc4E45D419950511e474C7B9Ed348A4a716c'
    wormhole_chainid: 2
  polygon-main:
    core_emitter: '0xabbce6c0c2c7cd213f4c69f8a685f6dfc1848b6e3f31dd15872f4e777d5b3e86'
    dola_chain_id: 5
    lending_portal: '0x2d6AEc91C128de330fEfF624ce660264e352567C'
    pools:
      MATIC:
        dola_chain_id: 5
        dola_pool_id: 5
        pool_address: '0x0000000000000000000000000000000000000000'
        pool_name: MATIC
        pool_weight: 1
      USDC:
        dola_chain_id: 5
        dola_pool_id: 2
        pool_address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'
        pool_name: USDC
        pool_weight: 1
      USDT:
        dola_chain_id: 5
        dola_pool_id: 1
        pool_address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F'
        pool_name: USDT
        pool_weight: 1
      WBTC:
        dola_chain_id: 5
        dola_pool_id: 0
        pool_address: '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6'
        pool_name: WBTC
        pool_weight: 1
    scan_rpc_url: https://api.polygonscan.com/api
    graphql_url: https://api.studio.thegraph.com/query/48530/polygondolarelayer/version/latest
    system_portal: '0x228b0e752c02FdA564Bac536219d2666E2e0A357'
    tokens:
      MATIC:
        address: '0x0000000000000000000000000000000000000000'
        decimals: 18
        dola_pool_id: 5
      USDC:
        address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'
        decimals: 6
        dola_pool_id: 2
      USDT:
        address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F'
        decimals: 6
        dola_pool_id: 1
      WBTC:
        address: '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6'
        decimals: 8
        dola_pool_id: 0
    wormhole: '0x7A4B5a56256163F07b2C80A7cA55aBE66c4ec4d7'
    wormhole_adapter_pool: '0x4445c48e9B70F78506E886880a9e09B501ED1E13'
    wormhole_chainid: 5
    wormhole_instant_consistency: 200
    wormhole_finality_consistency: 200
  polygon-test:
    core_emitter: '0x4f9f241cd3a249e0ef3d9ece8b1cd464c38c95d6d65c11a2ddd5645632e6e8a0'
    lending_portal: '0x1aDA087B6c051C77003966d669D1149d0c2dEE5F'
    scan_rpc_url: https://api-testnet.polygonscan.com/api
    system_portal: '0x2c0E6c7F14014F9D5D89F12DaB5c2Ea6eEfc481b'
    graphql_url: https://api.studio.thegraph.com/query/48530/mumbaidola/version/latest
    pools:
      MATIC:
        dola_chain_id: 5
        dola_pool_id: 5
        pool_address: '0x0000000000000000000000000000000000000000'
        pool_name: MATIC
        pool_weight: 1
      USDC:
        dola_chain_id: 5
        dola_pool_id: 2
        pool_address: '0x2A66Cf335a4cDd0D3b3904254520556C9894A266'
        pool_name: USDC
        pool_weight: 1
      USDT:
        dola_chain_id: 5
        dola_pool_id: 1
        pool_address: '0x8Ad2188372a9321b5cfb1fC0AC0BbA75772424c6'
        pool_name: USDT
        pool_weight: 1
      WBTC:
        dola_chain_id: 5
        dola_pool_id: 0
        pool_address: '0xE0332679Baf5d55Da6dbcF8199322F111c7005D8'
        pool_name: WBTC
        pool_weight: 1
    tokens:
      MATIC:
        address: '0x0000000000000000000000000000000000000000'
        decimals: 18
        dola_pool_id: 5
      USDC:
        address: '0x2A66Cf335a4cDd0D3b3904254520556C9894A266'
        decimals: 18
        dola_pool_id: 2
      USDT:
        address: '0x8Ad2188372a9321b5cfb1fC0AC0BbA75772424c6'
        decimals: 18
        dola_pool_id: 1
      WBTC:
        address: '0xE0332679Baf5d55Da6dbcF8199322F111c7005D8'
        decimals: 18
        dola_pool_id: 0
    wormhole: '0x0CBE91CF822c73C2315FB05100C2F714765d5c20'
    wormhole_adapter_pool: '0x83B787B99B1f5E9D90eDcf7C09E41A5b336939A7'
    wormhole_chainid: 5
    wormhole_instant_consistency: 200
    wormhole_finality_consistency: 200
  polygon-zk-test:
    btc: '0x9895bcd049eE00560599b1458fC2436793E3E011'
    lending_portal: '0x4e7AE7De13Db1587EA9B6C306299f66c3991D57e'
    scan_rpc_url: https://api-testnet-zkevm.polygonscan.com/api
    system_portal: '0x174C29259764719f4c4e6a92dDd817847864f7B1'
    usdc: '0x2bb68D45ce273e5eed8D10193B98a9e33259f2B1'
    usdt: '0xABC8849BB0fF39EDF2CfC41d23C307f0FEaE1714'
    wormhole: '0x0000000000000000000000000000000000000000'
    wormhole_adapter_pool: '0x5DAa53dd528dbc1d885Ad5E9D963f8368F9A39F0'
    wormhole_chainid: 7
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
