# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  default: development
  development:
    wormhole_chainid: 0
    wormhole: "0x0000000000000000000000000000000000000000"
  goerli:
    wormhole_chainid: 2
    wormhole: "0x706abc4E45D419950511e474C7B9Ed348A4a716c"
  bsc-test:
    wormhole_chainid: 4
    wormhole: "0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D"
    usdt: "0xdB51a2C9b0b1D9910b04F23AC8c58647f95C68A6"
    usdt_pool: "0x92e6C5E5466aD68d19fdc520FCa9f8F75996EB79"
    btc: "0x5a0B225Cbe96a87e4173D386CAaB0AC79771E940"
    btc_pool: "0x33688544d58ff4c1d9F608F7bCf3954aD5cc688e"
  polygon-test:
    wormhole_chainid: 5
    wormhole: "0x0CBE91CF822c73C2315FB05100C2F714765d5c20"
  avax-test:
    wormhole_chainid: 6
    wormhole: "0x7bbcE28e64B3F8b84d876Ab298393c38ad7aac4C"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
