dotenv: .env
networks:
  default: bsc-test
  sui-devnet:
    node_url: https://fullnode.devnet.sui.io:443
    packages:
      DolaProtocol: '0xc1e060ebede02d546495912929894ba4f578fa5c018940bf2e8ed6ae8f4afcee'
      ExternalInterfaces: '0x637386bc0bf3c4f7caa920bb64a38b4eee9c5a599f0dc56674db8370ee0fbb2e'
      GenesisProposal: '0x7e1b98256f8b61c4215ebf91f5e4e698c6f7c6c67346d9246a514e93f8e259ed'
      TestCoins: '0x3a7fb8adf7acf191fe750d1e39be145695aae8d086d3965ac321323e93719bed'
      Wormhole: '0xa799ed12eb76079797d051a09289294451543f6ade7cbd967f5c3659ee7e0bd3'
  sui-localnet:
    node_url: http://127.0.0.1:9000
  sui-testnet:
    node_url: https://fullnode.testnet.sui.io:443
sui_wallets:
  from_mnemonic:
    Oracle: ${ORACLE_MNEMONIC}
    Relayer0: ${RELAYER0_MNEMONIC}
    Relayer1: ${RELAYER1_MNEMONIC}
    Relayer2: ${RELAYER2_MNEMONIC}
    Relayer3: ${RELAYER3_MNEMONIC}
    TestAccount: ${TEST_ACCOUNT_MNEMONIC}
