dotenv: .env
networks:
  default: bsc-test
  sui-devnet:
    node_url: https://fullnode.devnet.sui.io:443
    packages:
      DolaProtocol: '0xcca01a337f1d1ecbed704dbcb675ce96198299ddab5a1c54c1d1f6ebd27e5b3f'
      ExternalInterfaces: '0x6f1c4d06cd7243502d7869695326af563a86119a93957ae12049d3617221339f'
      GenesisProposal: '0x2c504467eddd56974524d1f372ff4b134cfded7d079560daa09bfcffc1c9676a'
      TestCoins: '0x359914b8d1ba70483351dd973588d63be63b055549c790826c5c1d3e7087f6fe'
  sui-localnet:
    node_url: http://127.0.0.1:9000
  sui-testnet:
    node_url: https://fullnode.testnet.sui.io:443
sui_wallets:
  from_mnemonic:
    Oracle: ${ORACLE_MNEMONIC}
    Relayer0: ${RELAYER0_MNEMONIC}
    Relayer1: ${RELAYER1_MNEMONIC}
    Relayer2: ${RELAYER2_MNEMONIC}
    Relayer3: ${RELAYER3_MNEMONIC}
    TestAccount: ${TEST_ACCOUNT_MNEMONIC}
