[package]
name = "Serde"
version = "0.0.1"

[dependencies]
# Use sui-cli v0.15.0
Sui = { local = "/Users/daiwei/project/chainx/meta/sui/sui/crates/sui-framework" }

[addresses]
serde = "0x0"
sui = "0x2"
