[package]
name = "Oracle"
version = "0.0.1"

[addresses]
oracle = "0x0"
sui = "0x2"
pyth = "0xa446c4a37c0bb69d03357c1a52d60da0b434048226d5f3feffdb693586bea861"
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "d050ad1d67a5b7da9fb65030aad12ef5d774ccad"

[dependencies.Pyth]
git = "https://github.com/OmniBTC/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "8601609d6f4f64fb9a42ec7704aae3cf3a47e140"