[package]
name = "AppManager"
version = "0.0.1"

[addresses]
app_manager = "0x0"
governance = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Governance]
local = "../governance"
