[package]
name = "OmniPool"
version = "0.0.1"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
omnipool = "_"
serde = "_"
dola_types = "_"

[dev-addresses]
# sha256 "OmniBTC | DolaProtocol | OmniPool"
omnipool = "0x9ff66a4abb97848131c18ae17e346334ea4e888f07f18b3f8eaf3c49da1c95ec"
serde = "0xcb56c63012804b0defed1d1196b817aec2857df516b39355a2e35fb5d65d2fbe"
dola_types = "0x8b97658dd9f52ad00684467269e5dee7b3e6e7f763f9b1da68e7310a07794b39"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Serde]
local = "../serde"

[dependencies.DolaTypes]
local = "../dola_types"
