[package]
name = "OmniPool"
version = "0.0.1"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
omnipool = "_"
serde = "_"
dola_types = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "cb4ba0a57c998c60cbab65af31a64875d2588ca5"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Serde]
local = "../serde"

[dependencies.DolaTypes]
local = "../dola_types"
