[package]
name = "WormholeBridge"
version = "0.0.1"

[addresses]
wormhole_bridge = "0x0"
wormhole = "0x0"
serde = "0x0"
omnipool = "0x0"
app_manager = "0x0"
pool_manager = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "6c001d0c491d1481fd4b477881d320e2421a6517"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "4dee99ac5bb1f84ec3df1adbb04e0f925aaed263"

[dependencies.OmniPool]
local = "../omnipool"

[dependencies.Serde]
local = "../serde"

[dependencies.PoolManager]
local = "../omnicore/pool_manager"

[dependencies.AppManager]
local = "../omnicore/app_manager"
