[package]
name = "WormholeBridge"
version = "0.0.1"

[addresses]
wormhole_bridge = "0x0"
wormhole = "0x0"
serde = "0x0"
omnipool = "0x0"
app_manager = "0x0"
pool_manager = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "79100a5687881eef489f347629bf5b19e417cc8e"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "3b20c0a0966dd5c936c9584b12dcf3b6ccc956e9"

[dependencies.OmniPool]
local = "../omnipool"

[dependencies.Serde]
local = "../serde"

[dependencies.PoolManager]
local = "../omnicore/pool_manager"

[dependencies.AppManager]
local = "../omnicore/app_manager"
