[package]
name = "WormholeBridge"
version = "0.0.1"

[addresses]
wormhole_bridge = "0x0"
wormhole = "0x0"
serde = "0x0"
omnipool = "0x0"
dola_types = "0x0"
app_manager = "0x0"
pool_manager = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "21fcff72bef3b12f600da861b7708ca5f30d9512"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "e6e160614e1b2aeaaad3fd1c587571a3ee8a082d"

[dependencies.OmniPool]
local = "../omnipool"

[dependencies.DolaTypes]
local = "../dola_types"

[dependencies.Serde]
local = "../serde"

[dependencies.PoolManager]
local = "../omnicore/pool_manager"

[dependencies.AppManager]
local = "../omnicore/app_manager"
