[package]
name = "Lending"
version = "0.0.1"

[addresses]
lending = "0x0"
wormhole_bridge = "0x0"
pool_manager = "0x0"
app_manager = "0x0"
governance = "0x0"
oracle = "0x0"
serde = "0x0"
wormhole = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "6c001d0c491d1481fd4b477881d320e2421a6517"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
subdir = "sui/wormhole"
rev = "8f7150ac22da1171e99c6f0c5e51f33de5f63f75"

[dependencies.Serde]
local = "../../serde"

[dependencies.WormholeBridge]
local = "../../wormhole_bridge"

[dependencies.AppManager]
local = "../app_manager"

[dependencies.PoolManager]
local = "../pool_manager"

[dependencies.Governance]
local = "../governance"

[dependencies.Oracle]
local = "../oracle"
