[package]
name = "AppManager"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "bf4065c04b8d7462047955abeea0aa9e11221088" }
Serde = { local = "../../serde" }

[addresses]
app_manager = "0xff83a554f6638b839bffe3970acf00c20e2f731c"
serde = "0x2653e605c5e0fc39d364b51c39f3dafab62c8cdd"
sui = "0x2"
