[package]
name = "OmniPool"
version = "0.0.1"

[addresses]
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"
serde = "0x0"
omnipool = "0x0"
dola_types = "0x0"
governance = "0x0"
sui = "0x2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "d050ad1d67a5b7da9fb65030aad12ef5d774ccad"

[dependencies.DolaTypes]
local = "../dola_types"

[dependencies.Serde]
local = "../serde"

[dependencies.Governance]
local = "../governance"
